// Generated by CoffeeScript 1.6.3
(function() {
  var assert, procedure, sinon;

  procedure = require('../lib/procedure');

  assert = require('assert');

  sinon = require('sinon');

  describe('procedure', function() {
    return it('should call all procedures', function(done) {
      var func, proc1, proc2, proc3;
      proc1 = sinon.spy(function(next) {
        var func;
        assert(typeof next === 'function');
        func = function() {
          next('hello world!');
          return next();
        };
        return setTimeout(func, 100);
      });
      proc2 = sinon.spy(function(str, next) {
        assert(str === 'hello world!');
        assert(typeof next === 'function');
        return next(1, 2, 3);
      });
      proc3 = sinon.spy(function(a, b, c, next) {
        assert(a === 1 && b === 2 && c === 3);
        assert(typeof next === 'function');
        return next();
      });
      procedure([proc1, proc2, proc3]);
      func = function() {
        assert(proc1.calledOnce);
        assert(proc2.calledOnce);
        assert(proc3.calledOnce);
        return done();
      };
      return setTimeout(func, 200);
    });
  });

}).call(this);
